# Generated by Django 5.2.7 on 2025-10-17 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miércoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sábado')], max_length=3)),
                ('hora', models.TimeField()),
                ('nivel', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=1)),
                ('cupos', models.PositiveSmallIntegerField(default=16)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='gimnasio.coach')),
            ],
            options={
                'ordering': ['dia', 'hora'],
            },
        ),
    ]
